version: '3'
services:
  shima:
    build: .
    depends_on:
      - db
      - lava
  lava:
    image: fredboat/lavalink:master
    volumes:
      - ${PWD}/application.yml:/opt/Lavalink/application.yml
    expose:
      - "2333"
  db:
    image: postgres:alpine
    restart: always
    volumes:
      - ${HOME}/Shimakaze-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
    expose:
      - "5432"
